version: '3.8'

services:
  codeagent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codeagent-web
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - CodeAgent__ProjectDirectory=/workspace
      - CodeAgent__DataDirectory=/app/data
      - CodeAgent__LogDirectory=/app/logs
      # Add your API keys here or use .env file
      # - OpenAI__ApiKey=${OPENAI_API_KEY}
      # - Anthropic__ApiKey=${ANTHROPIC_API_KEY}
    volumes:
      # Map test_workspace to container's workspace
      - ./test_workspace:/workspace
      # Persist data and logs
      - codeagent-data:/app/data
      - codeagent-logs:/app/logs
      # For development: uncomment to use local source code
      # - ./src/CodeAgent.Web/wwwroot:/app/wwwroot
    restart: unless-stopped
    networks:
      - codeagent-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

volumes:
  codeagent-data:
    driver: local
  codeagent-logs:
    driver: local

networks:
  codeagent-network:
    driver: bridge