version: '3.8'

services:
  codeagent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codeagent-web
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - CodeAgent__ProjectDirectory=/workspace
      - CodeAgent__DataDirectory=/app/data
      - CodeAgent__LogDirectory=/app/logs
      # WebSocket/SignalR settings
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore.SignalR=Debug
      - Logging__LogLevel__Microsoft.AspNetCore.Http.Connections=Debug
    volumes:
      - ./test_workspace:/workspace
      - codeagent-data:/app/data
      - codeagent-logs:/app/logs
    restart: unless-stopped
    networks:
      - codeagent-network

volumes:
  codeagent-data:
    driver: local
  codeagent-logs:
    driver: local

networks:
  codeagent-network:
    driver: bridge