name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 0.1.0-alpha.2)'
        required: true
        type: string

env:
  DOTNET_VERSION: '8.0.x'
  PROJECT_PATH: 'src/CodeAgent.CLI/CodeAgent.CLI.csproj'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Determine version
      id: version
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          VERSION=${GITHUB_REF#refs/tags/v}
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Publishing version: $VERSION"
        
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal
      
    - name: Pack
      run: dotnet pack ${{ env.PROJECT_PATH }} --configuration Release --no-build -p:PackageVersion=${{ steps.version.outputs.VERSION }} --output ./nupkg
      
    - name: Push to GitHub Packages
      run: |
        dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/cykonova/index.json"
        dotnet nuget push ./nupkg/*.nupkg --source "github" --skip-duplicate
      
    - name: Push to NuGet.org (optional)
      if: secrets.NUGET_API_KEY != ''
      run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
      
    - name: Create Release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ steps.version.outputs.VERSION }}
        body: |
          ## CodeAgent ${{ steps.version.outputs.VERSION }}
          
          ### Installation
          ```bash
          dotnet tool install --global Cykonova.CodeAgent --version ${{ steps.version.outputs.VERSION }} --add-source https://nuget.pkg.github.com/cykonova/index.json
          ```
          
          ### Update
          ```bash
          dotnet tool update --global Cykonova.CodeAgent --version ${{ steps.version.outputs.VERSION }} --add-source https://nuget.pkg.github.com/cykonova/index.json
          ```
          
          ### What's Changed
          See [commits](https://github.com/cykonova/CodeAgent/commits/v${{ steps.version.outputs.VERSION }}) for details.
        draft: false
        prerelease: ${{ contains(steps.version.outputs.VERSION, 'alpha') || contains(steps.version.outputs.VERSION, 'beta') }}
        files: ./nupkg/*.nupkg